### ISSUE TITLE
Add confirmation before posting

### ISSUE THREAD

**Issue by jackbaty** [hjertnes/mb.el#1]
I've unintentionally posted a non-micro.blog related buffer twice now using post2mb. Yes, this is my fault for being fumble fingered but I feel there's a reasonable risk of accidentally posting private information when running post2mb from the wrong buffer.

Others may find it annoying, but I wouldn't mind a simple "Post current buffer to micro.blog? (Y/n)" prompt before the post is sent.

**Comment by hjertnes** [comment]
@jackbaty Done!

**Comment by jackbaty** [comment]
Works great, thanks!
